# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3096a188e37367c231fe2bbbdbe44c9e81ce9c5812abde63a3fd85866c16937e9b2177f0336817376a9831f7016430ae735fd7f9a976d9d7234d5a8af1da3d74

test:
  secret_key_base: f2fa05e369c212734e406e46b9f3d92ddc6516d313e21f0f780526a844190d67fa2d5ca097245e75bdfa3a8ce759ac2db9ab9a290049be3556fd7803ea06c422

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
